### RESOURCES ----------------------------------------------------------------------------------------
###############################################################################
# Author: Loïc TALIGNANI
# Affiliation: IRD_MIVEGEC / Université de Montpellier
# Aim: Configuration file for shave2.smk snakefile
# Date: 2022.10.05
# Use: Edit or de/comment (#) settings
# Latest modification:
# Done:
###############################################################################
resources:
  tmpdir: "$TMPDIR" # Temporary directory (default: '$TMPDIR')

### MODULES -----------------------------------------------------------------------------------
MODULES:
  BCFTOOLS: "module load bcftools/1.15.1"
  BWA: "module load bwa/0.7.17"
  FASTQC: "module load fastqc/0.11.8"
  FASTQSCREEN: "module load fastq-screen/0.13.0"
  PICARDTOOLS: "module load picard/2.23.5"
  GATK4: "module load gatk4/4.2.6.1"
  GATK3: "module load gatk/3.8"
  GRAPHVIZ: "module load graphviz/2.40.1"
  HTSLIB: "module load htslib/1.14"
  JAVA8: "module load java-jdk/8.0.112"
  MULTIQC: "module load multiqc/1.13"
  PYTHON3: "module load python/3.7"
  QUALIMAP: "module load qualimap/2.2.2b"
  R: "module load r/4.2.1"
  SAMTOOLS: "module load samtools/1.15.1"
  SLURM-DRMAA: "module load slurm-drmaa/1.0.8"
  SNAKEMAKE: "module load snakemake/7.7.0"
  TRIMMOMATIC: "module load trimmomatic/0.39 "
  VCFTOOLS: "module load vcftools/0.1.16"

### ENVIRONNEMENTS -----------------------------------------------------------------------------------
conda:
  Linux: # Conda Linux environement yaml files:
    bcftools: "workflow/envs/linux/bcftools-1.15.1.yaml" # Bcftools     ver. 1.15.1
    bedtools: "workflow/envs/linux/bedtools-2.30.0.yaml" # Bedtools     ver. 2.30.0
    bowtie2: "workflow/envs/linux/bowtie2-2.4.5.yaml" # Bowtie2      ver. 2.4.5
    bwa: "workflow/envs/linux/bwa-0.7.17.yaml" # BWA          ver. 0.7.17
    cutadapt: "workflow/envs/linux/cutadapt-4.1.yaml" # Cutadapt     ver. 4.1
    fastq-screen: "workflow/envs/linux/fastq-screen-0.15.2.yaml" # Fastq-Screen ver. 0.15.2
    fastqc: "workflow/envs/linux/fastqc-0.11.9.yaml" # FastQC       ver. 0.11.9
    gawk: "workflow/envs/linux/gawk-5.1.0.yaml" # Awk          ver. 5.1.0
    lofreq: "workflow/envs/linux/lofreq-2.1.5.yaml" # Lofreq       ver. 2.1.5
    multiqc: "workflow/envs/linux/multiqc-1.12.yaml" # MultiQC      ver. 1.12
    samtools: "workflow/envs/linux/samtools-1.15.1.yaml" # Samtools     ver. 1.15.1
    sickle-trim: "workflow/envs/linux/sickle-trim-1.33.yaml" # Sickle-trim  ver. 1.33
    gatk: "workflow/envs/linux/gatk-3.8.yaml" # gatk ver. 3.8
    gatk4: "workflow/envs/linux/gatk-4.3.0.0.yaml" # gatk ver. 4.3.0.0
    picard: "workflow/envs/linux/picard-2.27.5.yaml" # picard ver. 2.27.5
    qualimap: "workflow/envs/linux/qualimap-2.2.2.yaml" # Qualimap    vers. 2.2.2
    trimmomatic: "workflow/envs/linux/trimmomatic-0.39.yaml" # trimmomatic ver. 0.39

### GATK ---------------------------------------------------------------------------------------------
GATK:

### ALIGNER ------------------------------------------------------------------------------------------
aligner: "bwa" # Select your favorite aligner (default: 'bwa')
## Available options:
## 'bwa'     # Faster (default)
## 'bowtie2' # Slower, 'sensitivity' requiried and should be set (see below "Bowtie2" options)

### MARKDUPLICATE PROGRAM ----------------------------------------------------------------------------
markdup: "picard" # # Select your favorite Mark Duplicate Program (default: 'picard')
## Available options:
## 'picard'     # Picard MarkDuplicateSpark (default)
## 'samtools'   # samtools markdup

### TRIMMING PROGRAM ---------------------------------------------------------------------------------
trimmer:
  "trimmomatic" # Select your favorite trimmer tool
  ## Available options:
  ## "scickle" Trim reads per quality and length, in combination with Cutadapt rule
  ## "trimmomatic" Cut adaptors, trim reads per quality and length.

### TRIMMOMATIC --------------------------------------------------------------------------------------
trimmomatic:
  adapters:
    nextera: "resources/adapters/NexteraPE-PE.fa"
    truseq2-pe: "resources/adapters/TruSeq2-PE.fa"
    truseq2-se: "resources/adapters/TruSeq2-SE.fa"
    truseq3-pe: "resources/adapters/TruSeq3-PE.fa"
    truseq3-pe-2: "resources/adapters/TruSeq3-PE-2.fa"
    truseq3-se: "resources/adapters/TruSeq3-SE.fa"
  seedMisMatches: "2"
  palindromeClipTreshold: "30"
  simpleClipThreshold: "15"
  LeadMinTrimQual: "3"
  TrailMinTrimQual: "3"
  windowSize: "4"
  avgMinQual: "15"
  minReadLength: "50"
  phred: "-phred33"

### SICKLE-TRIM --------------------------------------------------------------------------------------
sickle-trim:
  command: "pe" # Reading (default and should be 'pe' for paired-end sequences)
  encoding: "sanger" # Quality encoding (dafault, and should be 'sanger')
  ## Available options (only for information):
  ## 'sanger'           # CASAVA >= 1.8 for "recent" Illumina reads (default)
  ## 'illumina'         # CASAVA 1.3 to 1.7 for "old" Illumina reads
  ## 'solexa'           # CASAVA < 1.3 for Solexa
  quality: "20" # Phred score limit (default: '30')
  length: "50" # Read length limit after trim (default: '50')

### CUTADAPT -----------------------------------------------------------------------------------------
cutadapt:
  length: "50" # Discard reads shorter than 'length' after trim (default: '50')
  kits: # Sequence of an adapter ligated to the 3' end of the first read
    truseq_for: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT"
    truseq_rev: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACGGATGACTATCTCGTATGCCGTCTTCTGCTTG"
    truseq: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA" # Illumina "TruSeq" or "ScriptSeq" based libraries kits
    nextera: "CTGTCTCTTATACACATC" # Illumina "Nextera" or "TruSight" based libraries kits
    small: "TGGAATTCTCGGGTGCCAAGG" # Illumina "Small" based libraries kits

### FASTQSCREEN --------------------------------------------------------------------------------------
fastq-screen:
  config: "config/fastq-screen.conf" # Path to the fastq-screen configuration file
  subset: 1000 # Don't use the whole sequence file, but sub-dataset of specified number of read (default: '1000') [INT] (0='all')
  aligner: "bwa" # Aligner for fastq-screen (default and should be 'bwa')
  ## Available options:
  ## 'bwa'     # Burrows-Wheeler Aligner (default, somme small genomes indexes provided, see 'fastq-screen.conf')
  ## 'bowtie'  # Bowtie (indexes not provided)
  ## 'bowtie2' # Bowtie2 (indexes not provided)

### REFERENCE ----------------------------------------------------------------------------------------
path: "resources/genomes/" # Path to genomes references
reference: "Anopheles-gambiae-PEST_CHROMOSOMES_AgamP4.fa" # Your reference, in fasta format
index: "Anopheles-gambiae-PEST_CHROMOSOMES_AgamP4.fa.fai"
dictionary: "Anopheles-gambiae-PEST_CHROMOSOMES_AgamP4.dict"
## Available options:
## 'GCA_018104305.1_AalbF3_genomic.fasta'                       # AalbF3
## 'Anopheles-gambiae-PEST_CHROMOSOMES_AgamP4.fa'               # AgamP4

species: "Aedes albopictus"
## Available options:
## "Aedes albopictus"
## "Anopheles gambiae"

### CONSENSUS ----------------------------------------------------------------------------------------
consensus:
  mincov: 10 # Minimum coverage, mask lower regions with 'N' (default: '10') [INT]
  minaf: 0.1 # Minimum allele frequency allowed (default: '0.1') [FLOAT]

### KNWON VARIATION SITES ----------------------------------------------------------------------------
alleles:

### BWA ----------------------------------------------------------------------------------------------
bwa:
  path: "resources/indexes/bwa/" # Path to BWA indexes

### BOWTIE2 ------------------------------------------------------------------------------------------
bowtie2:
  path: "resources/indexes/bowtie2/" # Path to Bowtie2 indexes
  sensitivity: "--very-sensitive" # Bowtie2 sensitivity preset (default: '--very-sensitive')
  ## Available options:
  ## '--very-fast'      # Same as options: -D 5 -R 1 -N 0 -L 22 -i S,0,2.50
  ## '--fast'           # Same as options: -D 10 -R 2 -N 0 -L 22 -i S,0,2.50
  ## '--sensitive'      # Same as options: -D 15 -R 2 -N 0 -L 22 -i S,1,1.15
  ## '--very-sensitive' # Same as options: -D 20 -R 3 -N 0 -L 20 -i S,1,0.50 (default)

### VARIANTFILTRATION --------------------------------------------------------------------------------
filtering:
  # Set to true in order to apply machine learning based recalibration of
  # quality scores instead of hard filtering.
  vqsr: false
  hard:
    # hard filtering as outlined in GATK docs
    # (https://gatkforums.broadinstitute.org/gatk/discussion/2806/howto-apply-hard-filters-to-a-call-set)
    snvs:
      {
        "myfilter": "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0",
      }
    indels: { "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0" }
hh